# Generated by Django 5.0.2 on 2024-03-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=35)),
                ('second_name', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
