# Generated by Django 5.0.2 on 2024-03-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_specialties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=35)),
                ('second_name', models.CharField(max_length=35)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Specialties',
        ),
    ]
