# Generated by Django 5.0.2 on 2024-03-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_rename_father_name_kaka_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=35)),
            ],
        ),
        migrations.DeleteModel(
            name='Kaka',
        ),
    ]
