# Generated by Django 5.0.2 on 2024-03-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0006_specialties_delete_kaka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialties',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
