# Generated by Django 5.0.2 on 2024-03-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_alter_specialties_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.RenameModel(
            old_name='Specialties',
            new_name='Specialte',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='father_name',
            new_name='last_name',
        ),
    ]
